debug: true

build:
  image: golang:1.5.1
  environment:
    - GOPATH=/guestbook-go
  commands:
   - ls -l
   - pwd

branches:
  - master
  - staging

deploy:
  kubernetes:
    image: quay.io/ukhomeofficedigital/drone-kubernetes:latest
    registry: quay.io
    replicationcontrollers:
      - guestbook-controller.json
    services: []
    token: eqpPIb5jFPUzurndqZrXFM9oW1VGusqY
    apiserver: http://10.0.0.118:8080
    namespace: default
    debug: true
    tag: v0.0.$$BUILD_NUMBER
    when:
      branch: master

notify:
  slack:
    webhook_url: $$SLACK_WEBHOOK
    channel: ops-team
    username: drone.io
    debug: true
    template: >
      build #{{ build.number }} finished with a {{ build.status }} status
